### ISSUE TITLE
debug BarChart slowness

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-plot#101]
BarCharts are currently ~3x slower than other charts. Let's investigate why. It may have to do with something here in `d3plus-plot`, but it also may be related to the code in `d3plus-shape` that draws the Bars: https://github.com/d3plus/d3plus-shape/blob/master/src/Shape/Bar.js

**Comment by cnavarreteliz** [comment]
![image](https://user-images.githubusercontent.com/5233593/40940305-6149693e-6815-11e8-9cbd-6207c9078a28.png)

This is Barchart performance (with example dataset ~12.000 records) in `v.0.7.8`

**Comment by cnavarreteliz** [comment]
![image](https://user-images.githubusercontent.com/5233593/40942507-745d0f42-681c-11e8-8788-cdd152eba093.png)

The half of time in Shape.js was spent rendering labels. If we want optimize d3plus-plot, the key is `d3plus-shape`.  The main difference that I see between Treemap and Barchart are labels in Axis. Maybe that is de root cause of the "laggy", and that have sense if you see that time execution of `Axis.js` is the double than `Shape.js`

The focus for optimize @davelandry must be centered in context (i.e. React) when you have more than one chart in the same page.

**Comment by davelandry** [comment]
@cnavarreteliz ahhh I thought you were saying the BarChart was slower than the other plot visualizations, like LinePlot and StackedArea. It makes sense that it takes longer because of the axes.

Please take a look at the [d3plus-react](https://github.com/d3plus/d3plus-react/blob/master/src/Viz.js) library and see if there is an optimization with React that can be done.
