### ISSUE TITLE
maximum call stack size exceeded in Google Chrome

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-plot#109]
### Expected Behavior

Trying to draw a bar chart in a JSfiddle using latest v7 d3plus plot, gives an error. Only seems to happen in chrome.

### Current Behavior
No chart renders instead I get the error: 
```
d3plus-plot.v0.7.full.min.js:7 Uncaught RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at n (d3plus-plot.v0.7.full.min.js:7)
    at x (d3plus-plot.v0.7.full.min.js:7)
    at d3plus-plot.v0.7.full.min.js:7
    at Array.forEach (<anonymous>)
    at n (d3plus-plot.v0.7.full.min.js:7)
    at x (d3plus-plot.v0.7.full.min.js:7)
    at d3plus-plot.v0.7.full.min.js:7
    at Array.forEach (<anonymous>)
    at n (d3plus-plot.v0.7.full.min.js:7)
```

### Steps to Reproduce (for bugs)

1. Goto https://jsfiddle.net/Lya86tv1/1/
2. change v0.6 to v0.7
3. click run

### Your Environment

* Browser Name: Chrome 67
* Operating System and Version: Operating system OS X 10.13

**Comment by davelandry** [comment]
@jspeis found the culprit all the way in [d3plus-common](https://github.com/d3plus/d3plus-common/commit/4001b452e923ba3101382c5706fd82f6043f377f). @frabarz this should also fix your maximum call stack size bug!

this is fixed with the latest d3plus-plot release, but I suggest blowing out node modules for any React project so that the sub-package is updated across the board until I can re-release all vizzes: https://jsfiddle.net/Lya86tv1/17/

**Comment by jspeis** [comment]
:+1: awesome, thanks for the fix & update!
